export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const SHOW_USERS = "SHOW_USERS"

export const CREATE_ROLE = "CREATE_ROLE"
export const UPDATE_ROLE = "UPDATE_ROLE"
export const DELETE_ROLE = "DELETE_ROLE"
export const SHOW_ROLES = "SHOW_ROLES"

export const CREATE_PERMISSION = "CREATE_PERMISSION"
export const UPDATE_PERMISSION = "UPDATE_PERMISSION"
export const DELETE_PERMISSION = "DELETE_PERMISSION"
export const SHOW_PERMISSIONS = "SHOW_PERMISSIONS"